[build]
builder = "DOCKERFILE"
dockerfilePath = "deploy/docker/Dockerfile.server"

[deploy]
startCommand = "/app/server"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 100

[[services]]
name = "api"

[[services]]
name = "nats"

[[services]]
name = "postgres"

[[services]]
name = "dashboard"
